kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-calico

networking:
  disableDefaultCNI: true  # Important for Calico
  podSubnet: "192.168.0.0/16"  # Calico default pod CIDR

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
        listenAddress: "127.0.0.1"
        protocol: TCP
  - role: worker
  - role: worker

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
      SystemdCgroup = true
