apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      component: kube-controller-manager
  endpoints:
  - port: https-metrics
    path: /metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    interval: 30s
