apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aaosa-cert
  namespace: default
spec:
  secretName: aaosa-tls
  dnsNames:
  - aaosainternational.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
